### ISSUE TITLE
提示的内核一致是SDK系统内核

### ISSUE THREAD

**Issue by savelove123** [HeartHappy/WebX5Core#2]
安装Demo后使用，有onCoreInitFinished和onViewInitFinished，onInstallFinish: 200 也有打印，但是LoadWebview一直提示是SDK系统内核，就算用debugtbs也是提示SDK系统内核

**Comment by HeartHappy** [comment]
需要重启，首次安装X5内核，重启app生效，X5官方文档有这说明
